version: "3.9"
services:

  backend:
    restart: "on-failure"
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file: ./backend/.env
    environment:
      DB_HOST: database
    networks:
      - p_semi

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - p_semi
    depends_on:
      - backend

networks:
  p_semi:
